kind: ConfigMap
apiVersion: v1
metadata:
  name: 38173418-keytab
  namespace: test-01
immutable: false
binaryData:
  38173418.keytab: >-
    BQIAAABGAAEAC0lELk9ISU8uR09WAAgzODE3MzQxOAAAAABlaMNQAQASACD5hKKVCcACYDQO5QDO6bHjCeMHKf8FsJ61cpYJR3He/AAAADYAAQALSUQuT0hJTy5HT1YACDM4MTczNDE4AAAAAGVow1ABABEAEKc3tXpKa1SQ/f2dyQDv5dgAAABGAAEAC0lELk9ISU8uR09WAAgzODE3MzQxOAAAAABlaMNQAQAUACA90N2T0JCCZjyPG5+Qxdc9Kv0pQyPjky77C+c/hThMzAAAADYAAQALSUQuT0hJTy5HT1YACDM4MTczNDE4AAAAAGVow1ABABMAEEd0sxZLNDUkwiKPDHj0QhQ=
