kind: ConfigMap
apiVersion: v1
metadata:
  name: mailrc-kraken
  namespace: odh-genomics
data:
  .mailrc: |-
    set from="NO-REPLY-KRAKEN@das.ohio.gov"
    set smtp=smtp://soccsmtp.das.ohio.gov:25
    set ssl-verify=ignore
