apiVersion: batch/v1
kind: Job
metadata:
  name: kraken-job-1-1
  namespace: test-01
spec:
  template:
    metadata:
      labels:
        app: kraken-1-1
    spec:
      restartPolicy: Never
      volumes:
        - name: keytab
          configMap:
            name: 38173418-keytab
            items:
            - key: 38173418.keytab
              path: 38173418.keytab
            defaultMode: 365
        - name: krb5-conf
          configMap:
            name: krb5-conf
            items:
            - key: krb5.conf
              path: krb5.conf
            defaultMode: 365
        - name: mailrc
          configMap:
            name: mailrc-kraken
            items:
            - key: .mailrc
              path: .mailrc
            defaultMode: 365
        - name: run-job
          configMap:
            name: job-kraken
            items:
            - key: job.sh
              path: job.sh
            defaultMode: 365
        - name: data-disk
          persistentVolumeClaim:
            claimName: test-01-data-space
        - name: ephemeral
          emptyDir:
            sizeLimit: 1Gi
      containers:
        - resources:
            limits:
              cpu: '3'
              ephemeral-storage: 2Gi
              memory: 8Gi
            requests:
              cpu: '1'
              ephemeral-storage: 1Gi
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          name: container
          env:
            - name: DATA
              value: /data
            - name: REFERENCE
              value: /data/reference
            - name: http_proxy
              value: http://proxyoit.ohio.gov:8080
            - name: https_proxy
              value: http://proxyoit.ohio.gov:8080
            - name: TEMP
              value: /temp01
          imagePullPolicy: Always
          volumeMounts:
            - name: keytab
              mountPath: /opt/app-home/38173418.keytab
              subPath: 38173418.keytab
            - name: krb5-conf
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            - name: mailrc
              mountPath: /opt/app-home/.mailrc
              subPath: .mailrc
            - name: run-job
              mountPath: /opt/app-home/job.sh
              subPath: job.sh
            - name: data-disk
              mountPath: /data
            - name: ephemeral
              mountPath: /temp01
          terminationMessagePolicy: File
          image: iopconttest-registry-quay-quay-enterprise.apps.iopconttest.css.id.ohio.gov/odh-genomics/test-build:1.1
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: timquay-01-config
      schedulerName: default-scheduler