kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-01-data-space
  namespace: test-01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
